name: felupe-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - pypardiso
  - pip
  - pip:
    - nbgitpuller
    - einsumt
    - tensortrax
    - matadi
    - h5py
    - meshio
    - trame
    - panel
    - pyvista
    - felupe
